
sudo: required

language: generic

dist: bionic

before_install:
    - sudo apt-get update
    - sudo apt-get install -y live-config live-build make git open-infrastructure-system-build

install:
    - make build

